### ISSUE TITLE
Credentials not working when password does not exist

### ISSUE THREAD

**Issue by pabloperezj** [splunk/addonfactory-ucc-library#231]
Hi,

Credentials are not working as expected when `password.conf` does not exist. I am using VT4Splunk app in Splunk Enterprise 9.0.3 (Debian GNU/Linux 11, Python 3.7). When accessing to Configuration page an ERR0005 is received with the following message:
```
"Unexpected error \"<class 'splunktaucclib.rest_handler.error.RestError'>\" from python handler: \"REST Error [500]: Internal Server Error -- Traceback (most recent call last):\n  File \"SPLUNK_HOME/etc/apps/TA-virustotal-app/bin/ta_virustotal_app/aob_py3/splunktaucclib/rest_handler/handler.py\", line 124, in wrapper\n    for name, data, acl in meth(self, *args, **kwargs):\n  File \"SPLUNK_HOME/etc/apps/TA-virustotal-app/bin/ta_virustotal_app/aob_py3/splunktaucclib/rest_handler/handler.py\", line 303, in _format_response\n    masked = self.rest_credentials.decrypt_for_get(name, data)\n  File \"SPLUNK_HOME/etc/apps/TA-virustotal-app/bin/ta_virustotal_app/aob_py3/splunktaucclib/rest_handler/credentials.py\", line 203, in decrypt_for_get\n    data[field_name] = clear_password[field_name]\nTypeError: 'NoneType' object is not subscriptable\n\". See splunkd.log/python.log for more details."
```

* If trying to reproduce the issue and fails, delete `local/password.conf` and it should work.

Checking the code in `credentials.py` I noticed something strange. Code in [here](https://github.com/splunk/addonfactory-ucc-library/blob/c371165292ab105a959b4afbecc67c3f855d9fd8/splunktaucclib/rest_handler/credentials.py#L389) catches CredentialNotExistException and returns None. However, when using `_get` function, for example [here](https://github.com/splunk/addonfactory-ucc-library/blob/c371165292ab105a959b4afbecc67c3f855d9fd8/splunktaucclib/rest_handler/credentials.py#L191), CredentialNotExistException is trying to be caught but this isn't never happening because `_get` already caught it.

I guess this isn't the expected behaviour. I edited the `_get` function not to catch the CredentialNotExistException and it works correctly. There are only two calls to `_get` function, [here](https://github.com/splunk/addonfactory-ucc-library/blob/c371165292ab105a959b4afbecc67c3f855d9fd8/splunktaucclib/rest_handler/credentials.py#L153) and [here](https://github.com/splunk/addonfactory-ucc-library/blob/c371165292ab105a959b4afbecc67c3f855d9fd8/splunktaucclib/rest_handler/credentials.py#L166) that don't catch that exception, but it can be fixed by adding:
```
try:
  original_clear_password = self._get(name)
except CredentialNotExistException:
  original_clear_password = None
```

The other three calls to `_get` function in the [file](https://github.com/splunk/addonfactory-ucc-library/blob/main/splunktaucclib/rest_handler/credentials.py) do expect to catch the exception. Other solution may be not to edit the `_get` function and replace the `except CredentialNotExistException:` by `if self._get(...) is None`. Both solutions are valid and work as expected.

**Comment by pabloperezj** [comment]
> @pabloperezj thanks for the detailed report and for the proposed fix, Ill review those. I will not be available for the next month, so if I don't have time to check it and merge, I'll ask someone from the team to do that.

Any news?

**Comment by artemrys** [comment]
@pabloperezj sorry for a delay and thanks for the ping!
I reproduced the issue and your fix makes sense.
From my side I'll see how it can be tested in the pipeline and I'll try to make a release today with a fix.
